#:schema node_modules/wrangler/config-schema.json
name = "1gem-incoming-leads"
main = "src/index.ts"
compatibility_date = "2024-07-29"

[vars]
LIMIT_COUNTRIES = true

routes = [
	{ pattern = "1gem.dev/send-lead/", zone_name = "1gem.dev" }
]

# KV Namespace docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "kvleads"
id = "7309d3517770414997a1c6e1f5bec333"

# Other docs reminder https://developers.cloudflare.com/workers/wrangler/configuration/
